"""
LLM interaction module for account brief generation.
"""

import json
from typing import List, Optional, TypeVar, Type, Union

from pydantic import BaseModel, Field, field_validator, ValidationError

T = TypeVar('T', bound=BaseModel)


class KeyTalkingPoint(BaseModel):
    """A single key talking point."""
    point: str = Field(..., description="The talking point text", min_length=10)
    priority: int = Field(default=1, ge=1, le=5, description="Priority level from 1-5")
    
    @field_validator('point')
    @classmethod
    def validate_point(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Talking point cannot be empty")
        return v.strip()


class CompetitiveInsight(BaseModel):
    """Insight about a competitor."""
    competitor: str = Field(..., description="Competitor name", min_length=1)
    insight: str = Field(..., description="Insight about the competitor", min_length=10)
    weakness: Optional[str] = Field(default=None, description="Potential weakness or differentiation opportunity")
    
    @field_validator('competitor', 'insight')
    @classmethod
    def validate_fields(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()


class AccountInsights(BaseModel):
    """Structured insights about an account."""
    company_summary: str = Field(..., description="Brief summary about the company", min_length=20)
    persona_insights: str = Field(..., description="Insights about the target persona", min_length=20)
    key_talking_points: List[KeyTalkingPoint] = Field(default_factory=list, description="List of key talking points")
    competitive_insights: List[CompetitiveInsight] = Field(default_factory=list, description="Competitive analysis")
    recommended_next_steps: List[str] = Field(default_factory=list, description="Recommended next steps")
    
    @field_validator('company_summary', 'persona_insights')
    @classmethod
    def validate_text_fields(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()
    
    @field_validator('recommended_next_steps')
    @classmethod
    def validate_next_steps(cls, v: List[str]) -> List[str]:
        return [step.strip() for step in v if step.strip()]


class EnhancedBriefContent(BaseModel):
    """Enhanced brief content generated by LLM."""
    enhanced_talking_points: List[str] = Field(default_factory=list, description="Enhanced talking points")
    competitive_positioning: str = Field(default="", description="Competitive positioning narrative")
    value_proposition: str = Field(default="", description="Value proposition for the company")
    custom_recommendations: List[str] = Field(default_factory=list, description="Custom recommendations")
    
    @field_validator('enhanced_talking_points', 'custom_recommendations')
    @classmethod
    def validate_list_fields(cls, v: List[str]) -> List[str]:
        return [item.strip() for item in v if item.strip()]


def validate_llm_response(data: Union[dict, str], model_class: Type[T]) -> T:
    """
    Validate LLM response against a Pydantic model.
    
    Args:
        data: Raw dictionary data from LLM response, or JSON string
        model_class: Pydantic model class to validate against
        
    Returns:
        Validated Pydantic model instance
        
    Raises:
        ValidationError: If the data doesn't match the model schema
        ValueError: If data cannot be parsed as JSON (when string provided)
    """
    if isinstance(data, str):
        try:
            data = json.loads(data)
        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON string: {e}") from e
    
    return model_class.model_validate(data)


def generate_insights(company: str, persona: str, competitors: List[str]) -> Optional[AccountInsights]:
    """
    Generate insights using LLM (placeholder for future implementation).
    
    Args:
        company: The company name
        persona: The target persona
        competitors: List of competitor names
        
    Returns:
        Validated AccountInsights model, or None if not implemented
    """
    # Placeholder for future LLM integration
    # Example usage:
    # raw_response = call_llm_api(...)
    # return validate_llm_response(raw_response, AccountInsights)
    return None


def enhance_brief_with_llm(brief_template: str, company: str, persona: str, competitors: List[str]) -> EnhancedBriefContent:
    """
    Enhance account brief with LLM-generated content (placeholder).
    
    Args:
        brief_template: The base brief template
        company: The company name
        persona: The target persona
        competitors: List of competitor names
        
    Returns:
        Validated EnhancedBriefContent model
    """
    # Placeholder for future LLM integration
    # Example usage:
    # raw_response = call_llm_api(...)
    # return validate_llm_response(raw_response, EnhancedBriefContent)
    return EnhancedBriefContent()
